import Head from 'next/head'
import { useEffect } from 'react';

export default function Home() {
  useEffect(() => {
    if (typeof window !== 'undefined' && window.Telegram && window.Telegram.WebApp) {
      window.Telegram.WebApp.ready();
      // You can use the Telegram Web App here
    } else {
    }
  }, []);
  function sendMessage(){
    if (typeof window !== 'undefined' && window.Telegram && window.Telegram.WebApp) {
      window.Telegram.WebApp.sendData("hello world");
    }
  }
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <a href='https://t.me/sueweetiesmyanmar/68'>
        Start-Up Ep : 6
      </a>
      <button onClick={sendMessage()}>
        send data
      </button>
    </>
  )
}
